const DEFAULT_CONTENT = {
  heroKicker: 'Willkommen',
  heroHeadline: 'Ihr Betrieb verdient eine Website, die überzeugt',
  heroSub: 'Modern, schnell und mobilfreundlich – gebaut, um neue Kundschaft zu gewinnen.',
  servicesTitle: 'Leistungen',
  services: [
    { name: 'Beratung', desc: 'Wir nehmen uns Zeit für Ihr Anliegen und finden die passende Lösung.' },
    { name: 'Umsetzung', desc: 'Zuverlässige, saubere Ausführung nach Ihren Wünschen.' },
    { name: 'Nachbetreuung', desc: 'Auch nach dem Termin sind wir für Sie erreichbar.' },
  ],
  aboutTitle: 'Über uns',
  aboutText: 'Seit vielen Jahren sind wir für unsere Kundschaft in der Umgebung da. Persönlich, zuverlässig und mit einem Blick fürs Detail.',
  aboutPoints: ['Persönliche Beratung', 'Faire Preise', 'Langjährige Erfahrung'],
  testimonials: [
    { quote: 'Sehr freundlich und kompetent – jederzeit wieder.', author: 'Zufriedene Kundschaft' },
    { quote: 'Genau das, was wir gesucht haben.', author: 'Stammkunde' },
  ],
  galleryCaption: 'Ein Einblick in unseren Betrieb',
  ctaTitle: 'Jetzt Kontakt aufnehmen',
  ctaText: 'Wir freuen uns auf Ihre Nachricht oder Ihren Anruf.',
};

const CATEGORY_CONTENT = {
  Restaurant: {
    heroKicker: 'Küche mit Charakter',
    heroHeadline: 'Gutes Essen, ehrlich gemacht',
    heroSub: 'Frische Zutaten, hausgemachte Gerichte und ein Ort, an dem man sich wohlfühlt.',
    servicesTitle: 'Speisekarte',
    services: [
      { name: 'Vorspeisen', price: 'ab 6 €', desc: 'Leichter Auftakt aus frischen, saisonalen Zutaten.' },
      { name: 'Hauptgerichte', price: 'ab 14 €', desc: 'Klassiker und Neuinterpretationen aus unserer Küche.' },
      { name: 'Desserts', price: 'ab 5 €', desc: 'Hausgemachte Süßspeisen zum Abschluss.' },
      { name: 'Getränke', price: 'ab 3 €', desc: 'Ausgewählte Weine, Softdrinks und Kaffeespezialitäten.' },
    ],
    aboutTitle: 'Unsere Geschichte',
    aboutText: 'Was als kleine Idee begann, ist heute ein fester Anlaufpunkt für alle, die gutes Essen und Gastfreundschaft schätzen. Wir kochen mit Liebe zum Detail und frischen, regionalen Zutaten.',
    aboutPoints: ['Täglich frisch gekocht', 'Regionale Zutaten', 'Gemütliche Atmosphäre'],
    testimonials: [
      { quote: 'Bestes Essen in der Nachbarschaft, sehr zu empfehlen.', author: 'Google-Bewertung' },
      { quote: 'Herzlicher Service und tolle Gerichte.', author: 'Stammgast' },
    ],
    galleryCaption: 'Impressionen aus Küche und Restaurant',
    ctaTitle: 'Tisch reservieren',
    ctaText: 'Rufen Sie uns an oder schreiben Sie uns – wir halten Ihnen gerne einen Platz frei.',
  },
  Café: {
    heroKicker: 'Kaffee & Gemütlichkeit',
    heroHeadline: 'Ihr Lieblingsplatz für eine gute Tasse Kaffee',
    heroSub: 'Handgemachter Kaffee, frisches Gebäck und ein ruhiger Ort zum Verweilen.',
    servicesTitle: 'Unser Angebot',
    services: [
      { name: 'Kaffeespezialitäten', price: 'ab 3 €', desc: 'Von Espresso bis Flat White – frisch geröstet.' },
      { name: 'Frühstück', price: 'ab 7 €', desc: 'Herzhaft oder süß, jeden Tag frisch zubereitet.' },
      { name: 'Kuchen & Gebäck', price: 'ab 4 €', desc: 'Täglich hausgemacht.' },
    ],
    aboutTitle: 'Über unser Café',
    aboutText: 'Bei uns treffen sich Nachbarschaft und Kaffeeliebhaber. Wir legen Wert auf faire Röstereien, hausgemachtes Gebäck und eine entspannte Atmosphäre zum Verweilen.',
    aboutPoints: ['Fair gehandelter Kaffee', 'Täglich frisch gebacken', 'Gemütliches Ambiente'],
    testimonials: [
      { quote: 'Bester Kaffee der Gegend, sehr sympathisches Team.', author: 'Google-Bewertung' },
      { quote: 'Perfekt zum Arbeiten und Entspannen.', author: 'Stammgast' },
    ],
    galleryCaption: 'Ein Blick in unser Café',
    ctaTitle: 'Schauen Sie vorbei',
    ctaText: 'Wir freuen uns auf Ihren Besuch – oder rufen Sie uns einfach an.',
  },
  Barber: {
    heroKicker: 'Klassisches Barbershop-Handwerk',
    heroHeadline: 'Präziser Schnitt, saubere Kante',
    heroSub: 'Haarschnitt, Bartpflege und Rasur auf hohem Niveau – bei uns oder als Termin online.',
    servicesTitle: 'Leistungen & Preise',
    services: [
      { name: 'Haarschnitt', price: 'ab 25 €', desc: 'Klassisch oder modern, ganz nach Ihrem Stil.' },
      { name: 'Bartpflege', price: 'ab 15 €', desc: 'Trimmen, Konturen, Pflege.' },
      { name: 'Rasur', price: 'ab 20 €', desc: 'Traditionelle Nassrasur mit heißem Handtuch.' },
      { name: 'Komplettpaket', price: 'ab 40 €', desc: 'Schnitt, Bart und Rasur im Set.' },
    ],
    aboutTitle: 'Über unseren Barbershop',
    aboutText: 'Handwerk, das man sieht und spürt. Unser Team bringt langjährige Erfahrung mit und legt Wert auf Präzision, Stil und eine entspannte Atmosphäre.',
    aboutPoints: ['Erfahrene Barbiere', 'Klassisches Handwerk', 'Termine online buchbar'],
    testimonials: [
      { quote: 'Bester Barber der Stadt, immer top Ergebnis.', author: 'Google-Bewertung' },
      { quote: 'Sehr professionell und freundlich.', author: 'Stammkunde' },
    ],
    galleryCaption: 'Einblicke in unseren Shop',
    ctaTitle: 'Termin vereinbaren',
    ctaText: 'Rufen Sie an oder schreiben Sie uns für Ihren nächsten Termin.',
  },
  Friseur: {
    heroKicker: 'Ihr Friseursalon',
    heroHeadline: 'Ihr Look, unsere Leidenschaft',
    heroSub: 'Von Schnitt über Farbe bis Styling – individuell auf Sie abgestimmt.',
    servicesTitle: 'Leistungen & Preise',
    services: [
      { name: 'Damenschnitt', price: 'ab 35 €', desc: 'Waschen, Schneiden, Föhnen.' },
      { name: 'Herrenschnitt', price: 'ab 22 €', desc: 'Klassisch oder trendig.' },
      { name: 'Farbe & Strähnen', price: 'ab 55 €', desc: 'Individuelle Farbberatung inklusive.' },
      { name: 'Styling', price: 'ab 25 €', desc: 'Für besondere Anlässe.' },
    ],
    aboutTitle: 'Über unseren Salon',
    aboutText: 'Wir verbinden aktuelle Trends mit persönlicher Beratung. Unser Team hört zu und findet den Look, der wirklich zu Ihnen passt.',
    aboutPoints: ['Individuelle Beratung', 'Aktuelle Techniken', 'Hochwertige Produkte'],
    testimonials: [
      { quote: 'Endlich ein Salon, der wirklich zuhört.', author: 'Google-Bewertung' },
      { quote: 'Immer ein tolles Ergebnis, sehr zu empfehlen.', author: 'Stammkundin' },
    ],
    galleryCaption: 'Einblicke in unseren Salon',
    ctaTitle: 'Termin buchen',
    ctaText: 'Vereinbaren Sie jetzt Ihren nächsten Salontermin.',
  },
  Fitnessstudio: {
    heroKicker: 'Training auf Ihrem Niveau',
    heroHeadline: 'Erreichen Sie Ihre Ziele – mit uns',
    heroSub: 'Modernes Equipment, persönliche Betreuung und ein Team, das Sie motiviert.',
    servicesTitle: 'Angebote',
    services: [
      { name: 'Mitgliedschaft Basic', price: 'ab 24,90 €/Mon.', desc: 'Freies Training an allen Geräten.' },
      { name: 'Personal Training', price: 'ab 45 €/Std.', desc: 'Individuelles 1:1-Coaching.' },
      { name: 'Kurse', price: 'inklusive', desc: 'Von Yoga bis HIIT – für jedes Level.' },
    ],
    aboutTitle: 'Über unser Studio',
    aboutText: 'Wir schaffen ein Umfeld, in dem Sie sich wohlfühlen und wachsen können – egal ob Einsteiger oder erfahrener Athlet.',
    aboutPoints: ['Moderne Geräte', 'Qualifizierte Trainer', 'Flexible Öffnungszeiten'],
    testimonials: [
      { quote: 'Super Atmosphäre und motivierende Trainer.', author: 'Google-Bewertung' },
      { quote: 'Endlich ein Studio, in dem ich dranbleibe.', author: 'Mitglied' },
    ],
    galleryCaption: 'Einblicke ins Studio',
    ctaTitle: 'Jetzt Probetraining sichern',
    ctaText: 'Vereinbaren Sie ein unverbindliches Probetraining.',
  },
  Einzelhandel: {
    heroKicker: 'Lokal einkaufen',
    heroHeadline: 'Qualität, die man sieht und spürt',
    heroSub: 'Sorgfältig ausgewählte Produkte und persönliche Beratung vor Ort.',
    servicesTitle: 'Unser Sortiment',
    services: [
      { name: 'Beratung', desc: 'Wir helfen Ihnen, das Richtige zu finden.' },
      { name: 'Sonderbestellungen', desc: 'Auf Wunsch besorgen wir, was Sie suchen.' },
      { name: 'Geschenkideen', desc: 'Individuell zusammengestellt.' },
    ],
    aboutTitle: 'Über unser Geschäft',
    aboutText: 'Als inhabergeführtes Geschäft legen wir Wert auf Qualität, persönliche Beratung und einen ehrlichen Umgang mit unserer Kundschaft.',
    aboutPoints: ['Persönliche Beratung', 'Sorgfältig ausgewählte Produkte', 'Lokal verwurzelt'],
    testimonials: [
      { quote: 'Super Beratung und tolle Auswahl.', author: 'Google-Bewertung' },
      { quote: 'Man merkt, dass hier mit Herz gearbeitet wird.', author: 'Stammkundin' },
    ],
    galleryCaption: 'Einblicke in unser Geschäft',
    ctaTitle: 'Besuchen Sie uns',
    ctaText: 'Wir freuen uns auf Ihren Besuch im Laden.',
  },
  'Online-Shop': {
    shop: true,
    heroKicker: 'Handgemacht & einzigartig',
    heroHeadline: 'Ihre Marke, online erlebbar',
    heroSub: 'Sorgfältig hergestellt, direkt bei uns bestellbar — schnell, persönlich, ohne Umwege.',
    servicesTitle: 'Produkte',
    services: [
      { name: 'Bestseller-Set', price: 'ab 29 €', desc: 'Unsere beliebtesten Produkte im praktischen Set.' },
      { name: 'Einzelstück', price: 'ab 19 €', desc: 'Sorgfältig von Hand gefertigt, in limitierter Auflage.' },
      { name: 'Geschenkbox', price: 'ab 39 €', desc: 'Schön verpackt, perfekt zum Verschenken.' },
    ],
    aboutTitle: 'Unsere Marke',
    aboutText: 'Was als Leidenschaftsprojekt begann, ist heute eine eigene kleine Marke. Wir stellen jedes Produkt mit Sorgfalt her und legen Wert auf Qualität statt Masse.',
    aboutPoints: ['Handgefertigt in kleinen Mengen', 'Sorgfältig ausgewählte Materialien', 'Persönlicher Kontakt bei Fragen'],
    testimonials: [
      { quote: 'Tolle Qualität, man merkt die Liebe zum Detail.', author: 'Verifizierter Kauf' },
      { quote: 'Schnelle Lieferung und liebevoll verpackt.', author: 'Kundin' },
    ],
    galleryCaption: 'Einblicke in unsere Werkstatt',
    ctaTitle: 'Fragen zu einer Bestellung?',
    ctaText: 'Schreiben Sie uns — wir melden uns schnellstmöglich zurück.',
    shippingInfo: 'Versand innerhalb Deutschlands in der Regel 2–4 Werktage. Bestellung per E-Mail — wir bestätigen Zahlung und Versand persönlich. [Platzhalter: Für den echten Verkauf braucht es außerdem eine rechtssichere Widerrufsbelehrung und AGB.]',
  },
};

export function getContent(category) {
  return CATEGORY_CONTENT[category] || DEFAULT_CONTENT;
}
