export const STYLES = [
  {
    id: 'minimal',
    name: 'Modern Minimal',
    description: 'Viel Weißraum, klare Linien, zurückhaltend',
    googleFont: 'Inter:wght@400;500;600;700;800',
    fontHeading: "'Inter', system-ui, sans-serif",
    fontBody: "'Inter', system-ui, sans-serif",
    radius: '6px',
    heroLayout: 'left',
    colors: {
      bg: '#ffffff',
      surface: '#f6f6f5',
      text: '#141414',
      muted: '#6b6b6b',
      line: '#e7e7e5',
      accent: '#141414',
      accentText: '#ffffff',
      chip: '#141414',
    },
  },
  {
    id: 'warm',
    name: 'Warm & Einladend',
    description: 'Cremefarben, weiche Formen, herzlich',
    googleFont: 'Playfair+Display:wght@500;600&family=DM+Sans:wght@400;500;600;700',
    fontHeading: "'Playfair Display', Georgia, serif",
    fontBody: "'DM Sans', system-ui, sans-serif",
    radius: '18px',
    heroLayout: 'center',
    colors: {
      bg: '#faf6f0',
      surface: '#f1e6d8',
      text: '#2b2318',
      muted: '#7c7365',
      line: '#e6dac8',
      accent: '#8a5d3b',
      accentText: '#fffaf4',
      chip: '#8a5d3b',
    },
  },
  {
    id: 'bold',
    name: 'Bold & Farbig',
    description: 'Dunkel, kräftige Akzentfarbe, selbstbewusst',
    googleFont: 'Poppins:wght@400;500;600;700;800',
    fontHeading: "'Poppins', system-ui, sans-serif",
    fontBody: "'Poppins', system-ui, sans-serif",
    radius: '16px',
    heroLayout: 'left',
    colors: {
      bg: '#12131a',
      surface: '#1b1d27',
      text: '#f6f6f8',
      muted: '#a3a3b0',
      line: '#2b2d3a',
      accent: '#ff6a3d',
      accentText: '#12131a',
      chip: '#ff6a3d',
    },
  },
  {
    id: 'elegant',
    name: 'Klassisch Elegant',
    description: 'Schwarz & Gold, edel, hochwertig',
    googleFont: 'Cormorant+Garamond:wght@500;600;700&family=Jost:wght@400;500;600',
    fontHeading: "'Cormorant Garamond', Georgia, serif",
    fontBody: "'Jost', system-ui, sans-serif",
    radius: '2px',
    heroLayout: 'center',
    colors: {
      bg: '#0c0c0d',
      surface: '#161616',
      text: '#f3efe6',
      muted: '#a79f8f',
      line: '#2a2a2a',
      accent: '#c9a24b',
      accentText: '#0c0c0d',
      chip: '#c9a24b',
    },
  },
  {
    id: 'pastell',
    name: 'Sanft & Verspielt',
    description: 'Pastellfarben, runde Formen, freundlich',
    googleFont: 'Quicksand:wght@500;600;700&family=Nunito:wght@400;500;600;700',
    fontHeading: "'Quicksand', system-ui, sans-serif",
    fontBody: "'Nunito', system-ui, sans-serif",
    radius: '24px',
    heroLayout: 'center',
    colors: {
      bg: '#fdf3f7',
      surface: '#f8e4ec',
      text: '#3a2c33',
      muted: '#8a7580',
      line: '#f0d5e0',
      accent: '#e07ba3',
      accentText: '#ffffff',
      chip: '#e07ba3',
    },
  },
  {
    id: 'natural',
    name: 'Natürlich & Erdig',
    description: 'Grüntöne, Bio-Charme, erdverbunden',
    googleFont: 'Fraunces:wght@500;600;700&family=Karla:wght@400;500;600;700',
    fontHeading: "'Fraunces', Georgia, serif",
    fontBody: "'Karla', system-ui, sans-serif",
    radius: '10px',
    heroLayout: 'left',
    colors: {
      bg: '#f5f1e8',
      surface: '#e8e1d0',
      text: '#2f3326',
      muted: '#6e6b58',
      line: '#ddd5bd',
      accent: '#5c7a52',
      accentText: '#f5f1e8',
      chip: '#5c7a52',
    },
  },
  {
    id: 'retro',
    name: 'Retro Vintage',
    description: 'Warme Erdtöne, nostalgischer Charme',
    googleFont: 'Abril+Fatface&family=Josefin+Sans:wght@400;500;600',
    fontHeading: "'Abril Fatface', Georgia, serif",
    fontBody: "'Josefin Sans', system-ui, sans-serif",
    radius: '4px',
    heroLayout: 'center',
    colors: {
      bg: '#f2e4cf',
      surface: '#e8d2ab',
      text: '#3d2b1f',
      muted: '#7a6552',
      line: '#d9bd94',
      accent: '#c1502e',
      accentText: '#f2e4cf',
      chip: '#c1502e',
    },
  },
  {
    id: 'tech',
    name: 'Tech & Futuristisch',
    description: 'Dunkel, elektrische Akzente, modern',
    googleFont: 'Space+Grotesk:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600',
    fontHeading: "'Space Grotesk', system-ui, sans-serif",
    fontBody: "'IBM Plex Sans', system-ui, sans-serif",
    radius: '10px',
    heroLayout: 'left',
    colors: {
      bg: '#0a0e17',
      surface: '#131a26',
      text: '#e8ecf5',
      muted: '#7c8699',
      line: '#212b3b',
      accent: '#35e0c9',
      accentText: '#0a0e17',
      chip: '#35e0c9',
    },
  },
  {
    id: 'nordic',
    name: 'Skandinavisch',
    description: 'Kühl, hell, reduziert',
    googleFont: 'Bitter:wght@600;700&family=Mulish:wght@400;500;600',
    fontHeading: "'Bitter', Georgia, serif",
    fontBody: "'Mulish', system-ui, sans-serif",
    radius: '8px',
    heroLayout: 'left',
    colors: {
      bg: '#f7f8f9',
      surface: '#eceef0',
      text: '#22262b',
      muted: '#6b7278',
      line: '#dde1e4',
      accent: '#3d5a73',
      accentText: '#f7f8f9',
      chip: '#3d5a73',
    },
  },
  {
    id: 'playful',
    name: 'Verspielt & Bunt',
    description: 'Kräftige Farben, rund, energiegeladen',
    googleFont: 'Baloo+2:wght@600;700;800&family=Mulish:wght@400;500;600;700',
    fontHeading: "'Baloo 2', system-ui, sans-serif",
    fontBody: "'Mulish', system-ui, sans-serif",
    radius: '28px',
    heroLayout: 'center',
    colors: {
      bg: '#fff9f0',
      surface: '#ffe8b8',
      text: '#2b2118',
      muted: '#7a6f5c',
      line: '#ffe0a0',
      accent: '#ff5a5f',
      accentText: '#fff9f0',
      chip: '#ff5a5f',
    },
  },
];

export function getStyle(id) {
  return STYLES.find((s) => s.id === id) || STYLES[0];
}
